title: Coin Collector
description: A 2D platformer game built with Unity — collect coins, avoid enemies, and survive!
theme: jekyll-theme-cayman
url: "https://johnpranoy7.github.io"
baseurl: "/Coin-Collector"
